import type { AppType } from "./types"

export const mockApps: AppType[] = [
  {
    id: "1",
    name: "SocialConnect",
    icon: "/placeholder.svg?height=80&width=80",
    developer: "TechGiant Inc.",
    category: "Social",
    rating: 4.2,
    reviewCount: 2500000,
    downloads: 50000000,
    activeUsers: 25000000,
    lastUpdated: "2023-12-15",
    keyFeatures: [
      "Photo and video sharing",
      "Direct messaging",
      "Stories feature",
      "Live streaming",
      "Content discovery",
    ],
    reviewInsights: [
      {
        sentiment: "positive",
        text: "Users love the intuitive interface and quick response time of the app.",
      },
      {
        sentiment: "positive",
        text: "The new story feature is highly praised for its creative filters.",
      },
      {
        sentiment: "negative",
        text: "Many users report battery drain issues after the latest update.",
      },
      {
        sentiment: "negative",
        text: "Some users are experiencing crashes when uploading videos longer than 1 minute.",
      },
      {
        sentiment: "neutral",
        text: "Users request more customization options for their profiles.",
      },
    ],
    keywords: [
      { text: "intuitive", weight: 0.9, sentiment: "positive" },
      { text: "fast", weight: 0.8, sentiment: "positive" },
      { text: "creative", weight: 0.7, sentiment: "positive" },
      { text: "battery drain", weight: 0.8, sentiment: "negative" },
      { text: "crashes", weight: 0.7, sentiment: "negative" },
      { text: "filters", weight: 0.6, sentiment: "positive" },
      { text: "customization", weight: 0.5, sentiment: "neutral" },
      { text: "stories", weight: 0.9, sentiment: "positive" },
      { text: "messaging", weight: 0.7, sentiment: "positive" },
      { text: "slow", weight: 0.4, sentiment: "negative" },
      { text: "updates", weight: 0.5, sentiment: "neutral" },
      { text: "privacy", weight: 0.6, sentiment: "neutral" },
    ],
    ratingTimeline: [
      { month: "Jan", rating: 4.0 },
      { month: "Feb", rating: 4.1 },
      { month: "Mar", rating: 4.0 },
      { month: "Apr", rating: 3.8 },
      { month: "May", rating: 3.9 },
      { month: "Jun", rating: 4.2 },
      { month: "Jul", rating: 4.3 },
      { month: "Aug", rating: 4.2 },
      { month: "Sep", rating: 4.1 },
      { month: "Oct", rating: 4.2 },
      { month: "Nov", rating: 4.3 },
      { month: "Dec", rating: 4.2 },
    ],
  },
  {
    id: "2",
    name: "FitTracker Pro",
    icon: "/placeholder.svg?height=80&width=80",
    developer: "HealthTech Solutions",
    category: "Health & Fitness",
    rating: 4.7,
    reviewCount: 850000,
    downloads: 15000000,
    activeUsers: 8000000,
    lastUpdated: "2024-01-10",
    keyFeatures: ["Activity tracking", "Workout plans", "Nutrition logging", "Sleep analysis", "Community challenges"],
    reviewInsights: [
      {
        sentiment: "positive",
        text: "Users appreciate the comprehensive fitness tracking and detailed analytics.",
      },
      {
        sentiment: "positive",
        text: "The personalized workout recommendations receive high praise.",
      },
      {
        sentiment: "positive",
        text: "Many users report significant health improvements after using the app consistently.",
      },
      {
        sentiment: "negative",
        text: "Some users find the premium subscription too expensive.",
      },
      {
        sentiment: "neutral",
        text: "Users request more integration with other health apps and devices.",
      },
    ],
    keywords: [
      { text: "accurate", weight: 0.9, sentiment: "positive" },
      { text: "motivating", weight: 0.8, sentiment: "positive" },
      { text: "comprehensive", weight: 0.7, sentiment: "positive" },
      { text: "expensive", weight: 0.6, sentiment: "negative" },
      { text: "subscription", weight: 0.5, sentiment: "negative" },
      { text: "personalized", weight: 0.9, sentiment: "positive" },
      { text: "integration", weight: 0.6, sentiment: "neutral" },
      { text: "analytics", weight: 0.7, sentiment: "positive" },
      { text: "community", weight: 0.8, sentiment: "positive" },
      { text: "syncing", weight: 0.5, sentiment: "neutral" },
      { text: "results", weight: 0.8, sentiment: "positive" },
      { text: "interface", weight: 0.6, sentiment: "positive" },
    ],
    ratingTimeline: [
      { month: "Jan", rating: 4.5 },
      { month: "Feb", rating: 4.5 },
      { month: "Mar", rating: 4.6 },
      { month: "Apr", rating: 4.6 },
      { month: "May", rating: 4.7 },
      { month: "Jun", rating: 4.7 },
      { month: "Jul", rating: 4.8 },
      { month: "Aug", rating: 4.8 },
      { month: "Sep", rating: 4.7 },
      { month: "Oct", rating: 4.7 },
      { month: "Nov", rating: 4.7 },
      { month: "Dec", rating: 4.7 },
    ],
  },
  {
    id: "3",
    name: "DeliveryDash",
    icon: "/placeholder.svg?height=80&width=80",
    developer: "QuickServe Technologies",
    category: "Food & Drink",
    rating: 3.9,
    reviewCount: 1200000,
    downloads: 30000000,
    activeUsers: 12000000,
    lastUpdated: "2023-11-28",
    keyFeatures: [
      "Restaurant delivery",
      "Real-time order tracking",
      "Multiple payment options",
      "Scheduled deliveries",
      "Loyalty rewards program",
    ],
    reviewInsights: [
      {
        sentiment: "positive",
        text: "Users love the wide selection of restaurants and quick delivery times.",
      },
      {
        sentiment: "positive",
        text: "The real-time tracking feature is frequently mentioned as a standout feature.",
      },
      {
        sentiment: "negative",
        text: "Many complaints about incorrect orders and poor customer service response.",
      },
      {
        sentiment: "negative",
        text: "Users report high delivery fees compared to competitors.",
      },
      {
        sentiment: "neutral",
        text: "Requests for more filtering options when searching for restaurants.",
      },
    ],
    keywords: [
      { text: "fast", weight: 0.8, sentiment: "positive" },
      { text: "convenient", weight: 0.9, sentiment: "positive" },
      { text: "tracking", weight: 0.7, sentiment: "positive" },
      { text: "expensive", weight: 0.8, sentiment: "negative" },
      { text: "errors", weight: 0.7, sentiment: "negative" },
      { text: "customer service", weight: 0.6, sentiment: "negative" },
      { text: "selection", weight: 0.8, sentiment: "positive" },
      { text: "filters", weight: 0.5, sentiment: "neutral" },
      { text: "late", weight: 0.6, sentiment: "negative" },
      { text: "rewards", weight: 0.7, sentiment: "positive" },
      { text: "refunds", weight: 0.5, sentiment: "neutral" },
      { text: "app crashes", weight: 0.4, sentiment: "negative" },
    ],
    ratingTimeline: [
      { month: "Jan", rating: 4.0 },
      { month: "Feb", rating: 4.0 },
      { month: "Mar", rating: 3.9 },
      { month: "Apr", rating: 3.8 },
      { month: "May", rating: 3.7 },
      { month: "Jun", rating: 3.7 },
      { month: "Jul", rating: 3.8 },
      { month: "Aug", rating: 3.9 },
      { month: "Sep", rating: 3.9 },
      { month: "Oct", rating: 4.0 },
      { month: "Nov", rating: 3.9 },
      { month: "Dec", rating: 3.9 },
    ],
  },
  {
    id: "4",
    name: "StreamFlix",
    icon: "/placeholder.svg?height=80&width=80",
    developer: "MediaStream Inc.",
    category: "Entertainment",
    rating: 4.5,
    reviewCount: 3000000,
    downloads: 75000000,
    activeUsers: 40000000,
    lastUpdated: "2024-01-05",
    keyFeatures: [
      "Video streaming",
      "Offline downloads",
      "Personalized recommendations",
      "Multiple profiles",
      "Parental controls",
    ],
    reviewInsights: [
      {
        sentiment: "positive",
        text: "Users praise the vast content library and high streaming quality.",
      },
      {
        sentiment: "positive",
        text: "The offline download feature is highly valued by commuters and travelers.",
      },
      {
        sentiment: "negative",
        text: "Some users complain about frequent price increases for subscriptions.",
      },
      {
        sentiment: "negative",
        text: "Reports of buffering issues during peak hours.",
      },
      {
        sentiment: "neutral",
        text: "Requests for improved subtitle options and language support.",
      },
    ],
    keywords: [
      { text: "quality", weight: 0.9, sentiment: "positive" },
      { text: "content", weight: 0.9, sentiment: "positive" },
      { text: "downloads", weight: 0.8, sentiment: "positive" },
      { text: "expensive", weight: 0.7, sentiment: "negative" },
      { text: "buffering", weight: 0.6, sentiment: "negative" },
      { text: "recommendations", weight: 0.7, sentiment: "positive" },
      { text: "subtitles", weight: 0.5, sentiment: "neutral" },
      { text: "profiles", weight: 0.6, sentiment: "positive" },
      { text: "interface", weight: 0.7, sentiment: "positive" },
      { text: "updates", weight: 0.5, sentiment: "neutral" },
      { text: "original shows", weight: 0.8, sentiment: "positive" },
      { text: "cancellation", weight: 0.4, sentiment: "negative" },
    ],
    ratingTimeline: [
      { month: "Jan", rating: 4.3 },
      { month: "Feb", rating: 4.3 },
      { month: "Mar", rating: 4.4 },
      { month: "Apr", rating: 4.4 },
      { month: "May", rating: 4.5 },
      { month: "Jun", rating: 4.5 },
      { month: "Jul", rating: 4.6 },
      { month: "Aug", rating: 4.6 },
      { month: "Sep", rating: 4.5 },
      { month: "Oct", rating: 4.5 },
      { month: "Nov", rating: 4.5 },
      { month: "Dec", rating: 4.5 },
    ],
  },
]

